version: "3"

services:
  api-management:
    image: api-management
    build: 
      context: ..
      dockerfile: ./deploy/api.Dockerfile 
    restart: always 
    ports: 
      - "5000:5000"
    environment:
      SERVICE_CONFIG: ${SERVICE_CONFIG:-dev}
    depends_on:
      - mongo
    # links:
    #   - mongo
    networks:
      - proxynet

  mongo:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    networks:
      - proxynet

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/
    networks:
      - proxynet

networks:
  proxynet:
    name: custom_network